import type { Advisory, Job, Repo, SimulationPreset, StateStats } from "./types";

export const PRESETS: SimulationPreset[] = [
  {
    id: "lodash",
    name: "Pre-fill: Lodash",
    cvss: "HIGH (CVSS 7.4)",
    affectedCount: 6,
    payload: {
      ghsa_id: "GHSA-jf85-cpcp-j695",
      package: "lodash",
      severity: "high",
      summary: "Command injection in lodash via template function",
      vulnerable_range: ">= 4.0.0, < 4.17.21",
      first_patched_version: "4.17.21",
      cve: "CVE-2021-23337",
      target_org_scope: "ANSUJKMEHER in scope ALL",
      resolve_transitive: true,
      atomic_fanout: true,
    },
    affectedSample: [
      { repo: "ANSUJKMEHER/Sentinel", path: "/package.json", fromVersion: "lodash@4.17.15", toVersion: "4.17.21", status: "PATCHING" },
      { repo: "ANSUJKMEHER/The-Lenny-Growth-Assistant", path: "/package.json", fromVersion: "lodash@4.17.19", toVersion: "4.17.21", status: "READY" },
      { repo: "ANSUJKMEHER/AgriVision-Ai", path: "/package.json", fromVersion: "lodash@4.17.11", toVersion: "4.17.21", status: "READY" },
      { repo: "ANSUJKMEHER/SkillForge", path: "/client/package.json", fromVersion: "lodash@4.17.20", toVersion: "4.17.21", status: "READY" },
    ],
  },
  {
    id: "axios",
    name: "axios",
    cvss: "HIGH (CVSS 7.5)",
    affectedCount: 4,
    payload: {
      ghsa_id: "GHSA-rp65-9cf3-cjxr",
      package: "axios",
      severity: "high",
      summary: "Cross-Site Request Forgery in absolute URLs",
      vulnerable_range: ">= 0.8.1, < 1.6.0",
      first_patched_version: "1.6.0",
      cve: "CVE-2023-45857",
      target_org_scope: "ANSUJKMEHER in scope ALL",
      resolve_transitive: true,
      atomic_fanout: true,
    },
    affectedSample: [
      { repo: "ANSUJKMEHER/StreamSync", path: "/package.json", fromVersion: "axios@0.21.1", toVersion: "1.6.0", status: "READY" },
      { repo: "ANSUJKMEHER/hiver", path: "/src/package.json", fromVersion: "axios@0.27.2", toVersion: "1.6.0", status: "READY" },
      { repo: "ANSUJKMEHER/DocExtract-LLM", path: "/package.json", fromVersion: "axios@1.5.0", toVersion: "1.6.0", status: "PATCHING" },
      { repo: "ANSUJKMEHER/GigShield-AI", path: "/package.json", fromVersion: "axios@0.21.4", toVersion: "1.6.0", status: "READY" },
    ],
  },
  {
    id: "jsonwebtoken",
    name: "jsonwebtoken",
    cvss: "CRITICAL (CVSS 9.8)",
    affectedCount: 3,
    payload: {
      ghsa_id: "GHSA-72xf-g2v4-qv37",
      package: "jsonwebtoken",
      severity: "critical",
      summary: "Insecure key retrieval allows arbitrary code execution",
      vulnerable_range: "< 9.0.0",
      first_patched_version: "9.0.0",
      cve: "CVE-2022-23529",
      target_org_scope: "ANSUJKMEHER in scope ALL",
      resolve_transitive: true,
      atomic_fanout: true,
    },
    affectedSample: [
      { repo: "ANSUJKMEHER/DailyAgent", path: "/package.json", fromVersion: "jsonwebtoken@8.5.1", toVersion: "9.0.0", status: "READY" },
      { repo: "ANSUJKMEHER/CrewDex_agent_portal", path: "/package.json", fromVersion: "jsonwebtoken@8.5.1", toVersion: "9.0.2", status: "PATCHING" },
      { repo: "ANSUJKMEHER/Link-Please", path: "/package.json", fromVersion: "jsonwebtoken@8.3.0", toVersion: "9.0.0", status: "READY" },
    ],
  },
];

export const MOCK_STATS: StateStats = {
  advisoriesSeen: 12,
  reposMonitored: 30,
  prsOpened: 18,
  prsMerged: 15,
  acceptanceRate: 88.5,
  cleanRepos: 26,
  pendingPatchRepos: 4,
  criticalHighCount: 3,
};

export const MOCK_ADVISORIES: Advisory[] = [
  {
    ghsa_id: "GHSA-jf85-cpcp-j695",
    package: "lodash",
    severity: "critical",
    summary: "Command injection via template function. Arbitrary execution via variable injection",
    vulnerableRange: "< 4.17.21",
    firstPatchedVersion: "4.17.21",
    cve: "CVE-2021-23337",
    source: "cron",
    dispatchStatus: "merged",
    prNumber: 142,
    publishedAt: "2024-03-15T14:32:00Z",
  },
  {
    ghsa_id: "GHSA-72xf-g2v4-qv37",
    package: "jsonwebtoken",
    severity: "critical",
    summary: "Insecure key retrieval allows arbitrary code execution through toString craft",
    vulnerableRange: "< 8.5.1",
    firstPatchedVersion: "9.0.0",
    cve: "CVE-2022-23529",
    source: "cron",
    dispatchStatus: "pushed",
    prNumber: 80,
    publishedAt: "2024-03-14T09:12:00Z",
  },
  {
    ghsa_id: "GHSA-rp65-9cf3-cjxr",
    package: "axios",
    severity: "high",
    summary: "Cross-Site Request Forgery in absolute URLs. Session header leakage during redirects",
    vulnerableRange: ">= 0.8.1, < 1.6.0",
    firstPatchedVersion: "1.6.0",
    cve: "CVE-2023-45857",
    source: "simulate",
    dispatchStatus: "simulated",
    publishedAt: "2024-03-12T18:40:00Z",
  },
  {
    ghsa_id: "GHSA-c7hr-j4mj-rv13",
    package: "semver",
    severity: "high",
    summary: "Regular Expression Denial of Service (ReDoS) catastrophic backtracking in range validation",
    vulnerableRange: "< 7.5.2",
    firstPatchedVersion: "7.5.2",
    cve: "CVE-2022-25883",
    source: "cron",
    dispatchStatus: "merged",
    prNumber: 198,
    publishedAt: "2024-03-11T11:05:00Z",
  },
  {
    ghsa_id: "GHSA-m4gz-62cw-9mq6",
    package: "undici",
    severity: "critical",
    summary: "Undici does not clear headers on cross-origin redirects. Authentication tokens leaked to third party",
    vulnerableRange: "< 5.26.5",
    firstPatchedVersion: "5.26.5",
    cve: "CVE-2023-45143",
    source: "cron",
    dispatchStatus: "queued",
    publishedAt: "2024-03-10T15:20:00Z",
  },
  {
    ghsa_id: "GHSA-g954-5hwp-ppcf",
    package: "sync-fetch",
    severity: "high",
    summary: "Server-Side Request Forgery inside internal worker. Sync worker fails host boundary check",
    vulnerableRange: "< 0.5.2",
    firstPatchedVersion: "0.5.2",
    cve: "CVE-2023-46811",
    source: "simulate",
    dispatchStatus: "simulated",
    publishedAt: "2024-03-08T08:00:00Z",
  },
  {
    ghsa_id: "GHSA-p6nc-w468-83gw",
    package: "fast-xml-parser",
    severity: "high",
    summary: "ReDoS in XML entities parser during tag attribute resolution. Unchecked payload depth causes thread halt",
    vulnerableRange: "< 4.2.5",
    firstPatchedVersion: "4.2.5",
    cve: "CVE-2023-3288",
    source: "cron",
    dispatchStatus: "merged",
    prNumber: 305,
    publishedAt: "2024-03-05T16:15:00Z",
  },
  {
    ghsa_id: "GHSA-cf4h-3jhx-xvhq",
    package: "follow-redirects",
    severity: "moderate",
    summary: "Open Redirect vulnerability in URL rewrite logic. Malformed proxy response handling",
    vulnerableRange: "< 1.15.4",
    firstPatchedVersion: "1.15.4",
    cve: "CVE-2023-26159",
    source: "simulate",
    dispatchStatus: "simulated",
    publishedAt: "2024-03-02T13:45:00Z",
  },
  {
    ghsa_id: "GHSA-4h84-7548-g5w4",
    package: "sheetjs",
    severity: "moderate",
    summary: "Prototype pollution via malformed workbook. Object key assignment bypass",
    vulnerableRange: "< 0.19.3",
    firstPatchedVersion: "0.19.3",
    cve: "CVE-2023-30533",
    source: "cron",
    dispatchStatus: "pushed",
    prNumber: 119,
    publishedAt: "2024-02-28T10:10:00Z",
  },
  {
    ghsa_id: "GHSA-v845-jxx5-vc9f",
    package: "qs",
    severity: "low",
    summary: "qs does not restrict array limit parameter accurately. Memory starvation on massive nested array strings",
    vulnerableRange: "< 6.11.0",
    firstPatchedVersion: "6.11.0",
    cve: "CVE-2022-24999",
    source: "cron",
    dispatchStatus: "merged",
    prNumber: 74,
    publishedAt: "2024-02-20T17:50:00Z",
  },
  {
    ghsa_id: "GHSA-3669-72x9-7p9v",
    package: "express",
    severity: "moderate",
    summary: "Bypass of path traversal protections when handling malformed query encoding",
    vulnerableRange: "< 4.19.2",
    firstPatchedVersion: "4.19.2",
    cve: "CVE-2024-29041",
    source: "cron",
    dispatchStatus: "merged",
    prNumber: 210,
    publishedAt: "2024-02-18T12:00:00Z",
  },
  {
    ghsa_id: "GHSA-w5p7-h5w8-2hfq",
    package: "minimatch",
    severity: "high",
    summary: "ReDoS vulnerability in glob expansion engine with nested brace patterns",
    vulnerableRange: "< 3.0.5",
    firstPatchedVersion: "3.0.5",
    cve: "CVE-2022-3517",
    source: "simulate",
    dispatchStatus: "simulated",
    publishedAt: "2024-02-15T09:30:00Z",
  },
];

export const MOCK_REPOS: Repo[] = [
  {
    repo: "ANSUJKMEHER/Sentinel",
    description: "Advisory-first, org-wide security automation platform",
    defaultBranch: "main",
    private: false,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 38,
    lastSeenAt: Math.floor(Date.now() / 1000) - 180,
  },
  {
    repo: "ANSUJKMEHER/The-Lenny-Growth-Assistant",
    description: "AI growth assistant and knowledge retrieval agent",
    defaultBranch: "main",
    private: false,
    status: "monitored",
    manifestEngines: ["package.json v2", "pnpm-lock v9"],
    dependencyCount: 84,
    lastSeenAt: Math.floor(Date.now() / 1000) - 420,
  },
  {
    repo: "ANSUJKMEHER/AgriVision-Ai",
    description: "Computer vision and crop telemetry pipeline",
    defaultBranch: "main",
    private: false,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 92,
    lastSeenAt: Math.floor(Date.now() / 1000) - 860,
  },
  {
    repo: "ANSUJKMEHER/hiver",
    description: "Multi-tenant collaboration and workflow orchestrator",
    defaultBranch: "main",
    private: false,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 65,
    lastSeenAt: Math.floor(Date.now() / 1000) - 1440,
  },
  {
    repo: "ANSUJKMEHER/DailyAgent",
    description: "Autonomous task planner and daily executive assistant",
    defaultBranch: "main",
    private: true,
    status: "monitored",
    manifestEngines: ["package.json v2", "yarn.lock v1"],
    dependencyCount: 47,
    lastSeenAt: Math.floor(Date.now() / 1000) - 2100,
  },
  {
    repo: "ANSUJKMEHER/SkillForge",
    description: "AI-powered skill mapping and learning platform",
    defaultBranch: "main",
    private: false,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 56,
    lastSeenAt: Math.floor(Date.now() / 1000) - 3600,
  },
  {
    repo: "ANSUJKMEHER/CrewDex_agent_portal",
    description: "Multi-agent coordination portal and execution engine",
    defaultBranch: "main",
    private: true,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 110,
    lastSeenAt: Math.floor(Date.now() / 1000) - 5400,
  },
  {
    repo: "ANSUJKMEHER/Extension",
    description: "Browser extension for real-time security alerts",
    defaultBranch: "main",
    private: true,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 22,
    lastSeenAt: Math.floor(Date.now() / 1000) - 7200,
  },
  {
    repo: "ANSUJKMEHER/Link-Please",
    description: "Smart link shortener and redirect security router",
    defaultBranch: "main",
    private: false,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 35,
    lastSeenAt: Math.floor(Date.now() / 1000) - 10800,
  },
  {
    repo: "ANSUJKMEHER/CrowdSentinel",
    description: "Crowdsourced incident response and threat intelligence",
    defaultBranch: "main",
    private: false,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 78,
    lastSeenAt: Math.floor(Date.now() / 1000) - 14400,
  },
  {
    repo: "ANSUJKMEHER/DocExtract-LLM",
    description: "Document parsing and RAG extraction service",
    defaultBranch: "main",
    private: false,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 44,
    lastSeenAt: Math.floor(Date.now() / 1000) - 18000,
  },
  {
    repo: "ANSUJKMEHER/StreamSync",
    description: "Real-time event streaming and synchronization harness",
    defaultBranch: "main",
    private: false,
    status: "monitored",
    manifestEngines: ["package.json v2", "lockfile v3"],
    dependencyCount: 61,
    lastSeenAt: Math.floor(Date.now() / 1000) - 21600,
  },
];

export const MOCK_JOBS: Job[] = [
  {
    jobId: "job-304",
    ghsaId: "GHSA-72xf-g2v4-qv37",
    repo: "ANSUJKMEHER/CrewDex_agent_portal",
    package: "jsonwebtoken",
    branch: "main branch • npm",
    fromRange: "8.5.1",
    toVersion: "9.0.2",
    status: "queued",
    prNumber: 304,
    ciStatus: "pending",
    ciDetails: "Executing tests (3/8)",
    updatedAt: Math.floor(Date.now() / 1000) - 12,
    isSimulated: true,
  },
  {
    jobId: "job-142",
    ghsaId: "GHSA-jf85-cpcp-j695",
    repo: "ANSUJKMEHER/Sentinel",
    package: "lodash",
    branch: "main • npm",
    fromRange: "4.17.15",
    toVersion: "4.17.21",
    status: "patched",
    prNumber: 142,
    prUrl: "https://github.com/ANSUJKMEHER/Sentinel/pull/142",
    ciStatus: "passing",
    ciDetails: "Checks Passed (14)",
    updatedAt: Math.floor(Date.now() / 1000) - 240,
  },
  {
    jobId: "job-89",
    ghsaId: "GHSA-c7hr-j4mj-rv13",
    repo: "ANSUJKMEHER/The-Lenny-Growth-Assistant",
    package: "semver",
    branch: "main • npm",
    fromRange: "7.3.5",
    toVersion: "7.5.2",
    status: "patched",
    prNumber: 89,
    prUrl: "https://github.com/ANSUJKMEHER/The-Lenny-Growth-Assistant/pull/89",
    ciStatus: "passing",
    ciDetails: "Checks Passed (6)",
    updatedAt: Math.floor(Date.now() / 1000) - 1080,
  },
  {
    jobId: "job-211",
    ghsaId: "GHSA-rp65-9cf3-cjxr",
    repo: "ANSUJKMEHER/DocExtract-LLM",
    package: "axios",
    branch: "main • npm",
    fromRange: "1.5.0",
    toVersion: "1.6.2",
    status: "conflict",
    prNumber: 211,
    prUrl: "https://github.com/ANSUJKMEHER/DocExtract-LLM/pull/211",
    ciStatus: "conflict",
    ciDetails: "Merge Conflict in package-lock.json",
    updatedAt: Math.floor(Date.now() / 1000) - 1920,
    error: "Lockfile conflict during atomic merge",
  },
  {
    jobId: "job-98",
    ghsaId: "GHSA-jf85-cpcp-j695",
    repo: "ANSUJKMEHER/StreamSync",
    package: "tokio",
    branch: "main • cargo",
    fromRange: "1.28.0",
    toVersion: "1.35.1",
    status: "queued",
    prNumber: 98,
    ciStatus: "pending",
    ciDetails: "Matrix check pending",
    updatedAt: Math.floor(Date.now() / 1000) - 3600,
    isSimulated: true,
  },
  {
    jobId: "job-441",
    ghsaId: "GHSA-m4gz-62cw-9mq6",
    repo: "ANSUJKMEHER/AgriVision-Ai",
    package: "spring-security",
    branch: "main • maven",
    fromRange: "5.8.0",
    toVersion: "5.8.8",
    status: "blocked",
    prNumber: 441,
    prUrl: "https://github.com/ANSUJKMEHER/AgriVision-Ai/pull/441",
    ciStatus: "failing",
    ciDetails: "Required CodeOwner review",
    updatedAt: Math.floor(Date.now() / 1000) - 4440,
    error: "Branch Rule Block: CodeOwner approval required",
  },
];
